### ISSUE TITLE
feat(Filter on the user traces)

### ISSUE THREAD

**Issue by damienld22** [zetapush/zetapush-devtools#15]
Hello,

I think it could useful to add a field to filter the user traces (like the filter on the owner or the macro name).
This could be in the terminal view and when an user type a text in the filter field, only the corresponding user traces will be displayed.

For example, if there are the traces :

"CreatePatientUser"
"OnNewMeasure::addInDatabase"
"OnNewMeasure::sendEventToUser"

when I type : "onNewMeasure", only this traces will be displayed :

"OnNewMeasure::addInDatabase"
"OnNewMeasure::sendEventToUser"

Thank you !

Damien

**Comment by ghoullier** [comment]
Closed by #8
